### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by Kobusken** [hakanuzunoglu/TWF-Dash#3]
First of all congratulations for the great job you have done with the dashboard. Tell you a couple of things that I see that can improve the dashboard.
- The PC's local time clock sometimes freezes and does not tell the time correctly.
- The flash light in iRacing would be nice if it blinks for a couple of seconds.
- If you could put an indicator of the SoF in iRacing of the session that would be great.

**Comment by hakanuzunoglu** [comment]
Hybrid MFD is in the works. Any feedback or inputs for hybrid would be much appreciated. Since I never race in hybrid, I truly have no idea.

I thought the light icon was flashing, I'll have a look.

**Comment by hakanuzunoglu** [comment]
The flasher is flashing but with slow speed, maybe that is why.

Also for the SoF, should this be shown by the end of race, or all time?

**Comment by Kobusken** [comment]
If you have a place to put it permanently, otherwise I think that with a 5-second alert informing it, it would also be a solution if there is no place to put it.

**Comment by hakanuzunoglu** [comment]
True. But then when would be the best time to show it? Beginning of the
race? End of the race?

**Comment by Kobusken** [comment]
At the beginning of the race I think it is the best

**Comment by hakanuzunoglu** [comment]
Cool, thanks!

I will include it in a release soon.

**Comment by hakanuzunoglu** [comment]
Ok, i have added the SoF in place of the irating gains, next to the incident count. They cycle every 5 seconds, so you will see SoF for 5, and then your gains and losses for 5.

Will release it with the next release.

**Comment by hakanuzunoglu** [comment]
Added the SoF.
