### ISSUE TITLE
Simhub v9 compatibility

### ISSUE THREAD

**Issue by DonutzAndCoffee** [hakanuzunoglu/TWF-Dash#5]
Hi! 
I am not sure what could be the root cause but after I upgraded to Simhub v9 beta the RPM gauge seems to be broken. It shows up as a white square instead of this blueish half circle. Any idea what could be the issue?
![2023-08-20 07_17_45-TWF DASH LITE (WPF Renderer)](https://github.com/hakanuzunoglu/TWF-Dash/assets/62204936/a9654f38-0798-4805-8fc6-1f5e24e0056f)

**Comment by hakanuzunoglu** [comment]
I did not get a chance to test the dash with SimHub v9 so far.

However, someone had a similar issue with simhub even in v8. His simhub was not able to display circular gauges properly at all. He was able to fix by reinstalling. I recommend checking with another dash that has circular gauges.

**Comment by DonutzAndCoffee** [comment]
I did a quick test. Circular gauge works in general.

**Comment by DonutzAndCoffee** [comment]
![2023-08-21 09_59_39-Window](https://github.com/hakanuzunoglu/TWF-Dash/assets/62204936/41fa3c99-5591-48d1-96bd-f28e812e0c85)

I switched here from WPF render engine to HTML render engine. Now it works fine.

**Comment by hakanuzunoglu** [comment]
Glad it worked for you. Will keep an eye when I start testing for SimHub V9.
